package com.cpf.mapper.transaction;

import com.cpf.beans.transaction.TraBartersDetails;

public interface TraBartersDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_barters_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String bardetailsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_barters_details
     *
     * @mbggenerated
     */
    int insert(TraBartersDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_barters_details
     *
     * @mbggenerated
     */
    int insertSelective(TraBartersDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_barters_details
     *
     * @mbggenerated
     */
    TraBartersDetails selectByPrimaryKey(String bardetailsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_barters_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TraBartersDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_barters_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TraBartersDetails record);
}