package com.cpf.mapper.transaction;

import com.cpf.beans.transaction.TraBidrecord;

public interface TraBidrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_bidrecord
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_bidrecord
     *
     * @mbggenerated
     */
    int insert(TraBidrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_bidrecord
     *
     * @mbggenerated
     */
    int insertSelective(TraBidrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_bidrecord
     *
     * @mbggenerated
     */
    TraBidrecord selectByPrimaryKey(String recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_bidrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TraBidrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_bidrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TraBidrecord record);
}