package com.cpf.mapper.transaction;

import com.cpf.beans.transaction.TraBarters;

public interface TraBartersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_barters
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String barorderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_barters
     *
     * @mbggenerated
     */
    int insert(TraBarters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_barters
     *
     * @mbggenerated
     */
    int insertSelective(TraBarters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_barters
     *
     * @mbggenerated
     */
    TraBarters selectByPrimaryKey(String barorderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_barters
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TraBarters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_barters
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TraBarters record);
}