package com.cpf.mapper.transaction;

import com.cpf.beans.transaction.TraCategories;

public interface TraCategoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_categories
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_categories
     *
     * @mbggenerated
     */
    int insert(TraCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_categories
     *
     * @mbggenerated
     */
    int insertSelective(TraCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_categories
     *
     * @mbggenerated
     */
    TraCategories selectByPrimaryKey(String cateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_categories
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TraCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_categories
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TraCategories record);
}