package com.cpf.mapper.transaction;

import com.cpf.beans.transaction.TraOfficialspecial;

public interface TraOfficialspecialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_officialspecial
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String officialid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_officialspecial
     *
     * @mbggenerated
     */
    int insert(TraOfficialspecial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_officialspecial
     *
     * @mbggenerated
     */
    int insertSelective(TraOfficialspecial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_officialspecial
     *
     * @mbggenerated
     */
    TraOfficialspecial selectByPrimaryKey(String officialid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_officialspecial
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TraOfficialspecial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_officialspecial
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TraOfficialspecial record);
}