package com.cpf.mapper.transaction;

import com.cpf.beans.transaction.TraPersonalspecial;

public interface TraPersonalspecialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_personalspecial
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String specialid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_personalspecial
     *
     * @mbggenerated
     */
    int insert(TraPersonalspecial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_personalspecial
     *
     * @mbggenerated
     */
    int insertSelective(TraPersonalspecial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_personalspecial
     *
     * @mbggenerated
     */
    TraPersonalspecial selectByPrimaryKey(String specialid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_personalspecial
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TraPersonalspecial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_personalspecial
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TraPersonalspecial record);
}