package com.cpf.mapper.transaction;

import com.cpf.beans.transaction.TraProduct;

public interface TraProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String productid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_product
     *
     * @mbggenerated
     */
    int insert(TraProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_product
     *
     * @mbggenerated
     */
    int insertSelective(TraProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_product
     *
     * @mbggenerated
     */
    TraProduct selectByPrimaryKey(String productid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TraProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TraProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TraProduct record);
}