package com.cpf.mapper.transaction;

import com.cpf.beans.transaction.TraSpecialordersDetails;

public interface TraSpecialordersDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_specialorders_details
     *
     * @mbggenerated
     */
    int insert(TraSpecialordersDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_specialorders_details
     *
     * @mbggenerated
     */
    int insertSelective(TraSpecialordersDetails record);
}