package com.cpf.mapper.transaction;

import com.cpf.beans.transaction.TraSpecialorders;

public interface TraSpecialordersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_specialorders
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String speorderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_specialorders
     *
     * @mbggenerated
     */
    int insert(TraSpecialorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_specialorders
     *
     * @mbggenerated
     */
    int insertSelective(TraSpecialorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_specialorders
     *
     * @mbggenerated
     */
    TraSpecialorders selectByPrimaryKey(String speorderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_specialorders
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TraSpecialorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_specialorders
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TraSpecialorders record);
}