package com.cpf.mapper.system;

import com.cpf.beans.system.Appversion;

public interface AppversionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appversion
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String verid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appversion
     *
     * @mbggenerated
     */
    int insert(Appversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appversion
     *
     * @mbggenerated
     */
    int insertSelective(Appversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appversion
     *
     * @mbggenerated
     */
    Appversion selectByPrimaryKey(String verid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appversion
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Appversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appversion
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Appversion record);
}