package com.cpf.mapper.system;

import com.cpf.beans.system.RelNewsView;

public interface RelNewsViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_news_view
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String viewid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_news_view
     *
     * @mbggenerated
     */
    int insert(RelNewsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_news_view
     *
     * @mbggenerated
     */
    int insertSelective(RelNewsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_news_view
     *
     * @mbggenerated
     */
    RelNewsView selectByPrimaryKey(String viewid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_news_view
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelNewsView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_news_view
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RelNewsView record);
}