package com.cpf.mapper.system;

import com.cpf.beans.system.RelQuestionAnswer;

public interface RelQuestionAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_question_answer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String answerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_question_answer
     *
     * @mbggenerated
     */
    int insert(RelQuestionAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_question_answer
     *
     * @mbggenerated
     */
    int insertSelective(RelQuestionAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_question_answer
     *
     * @mbggenerated
     */
    RelQuestionAnswer selectByPrimaryKey(String answerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_question_answer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelQuestionAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_question_answer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RelQuestionAnswer record);
}