package com.cpf.mapper.system;

import com.cpf.beans.system.RelUserLabel;

public interface RelUserLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_user_label
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_user_label
     *
     * @mbggenerated
     */
    int insert(RelUserLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_user_label
     *
     * @mbggenerated
     */
    int insertSelective(RelUserLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_user_label
     *
     * @mbggenerated
     */
    RelUserLabel selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_user_label
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelUserLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_user_label
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RelUserLabel record);
}