package com.cpf.mapper.system;

import com.cpf.beans.system.SysAds;

public interface SysAdsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ads
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String adid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ads
     *
     * @mbggenerated
     */
    int insert(SysAds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ads
     *
     * @mbggenerated
     */
    int insertSelective(SysAds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ads
     *
     * @mbggenerated
     */
    SysAds selectByPrimaryKey(String adid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ads
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysAds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ads
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysAds record);
}