package com.cpf.mapper.system;

import com.cpf.beans.system.SysNews;

public interface SysNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String newsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated
     */
    int insert(SysNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated
     */
    int insertSelective(SysNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated
     */
    SysNews selectByPrimaryKey(String newsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysNews record);
}