package com.cpf.mapper.system;

import com.cpf.beans.system.SysSecurityquestion;

public interface SysSecurityquestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_securityquestion
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String questionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_securityquestion
     *
     * @mbggenerated
     */
    int insert(SysSecurityquestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_securityquestion
     *
     * @mbggenerated
     */
    int insertSelective(SysSecurityquestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_securityquestion
     *
     * @mbggenerated
     */
    SysSecurityquestion selectByPrimaryKey(String questionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_securityquestion
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysSecurityquestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_securityquestion
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysSecurityquestion record);
}