package com.cpf.mapper.system;

import com.cpf.beans.system.SysTagsdictionary;

public interface SysTagsdictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tagsdictionary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String labelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tagsdictionary
     *
     * @mbggenerated
     */
    int insert(SysTagsdictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tagsdictionary
     *
     * @mbggenerated
     */
    int insertSelective(SysTagsdictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tagsdictionary
     *
     * @mbggenerated
     */
    SysTagsdictionary selectByPrimaryKey(String labelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tagsdictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysTagsdictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tagsdictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysTagsdictionary record);
}