package com.cpf.beans.system;

import java.util.Date;

public class Appversion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appversion.VERID
     *
     * @mbggenerated
     */
    private String verid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appversion.vernum
     *
     * @mbggenerated
     */
    private String vernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appversion.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appversion.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appversion.appurl
     *
     * @mbggenerated
     */
    private String appurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appversion.devicetype
     *
     * @mbggenerated
     */
    private String devicetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appversion.isreview
     *
     * @mbggenerated
     */
    private String isreview;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appversion.VERID
     *
     * @return the value of appversion.VERID
     *
     * @mbggenerated
     */
    public String getVerid() {
        return verid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appversion.VERID
     *
     * @param verid the value for appversion.VERID
     *
     * @mbggenerated
     */
    public void setVerid(String verid) {
        this.verid = verid == null ? null : verid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appversion.vernum
     *
     * @return the value of appversion.vernum
     *
     * @mbggenerated
     */
    public String getVernum() {
        return vernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appversion.vernum
     *
     * @param vernum the value for appversion.vernum
     *
     * @mbggenerated
     */
    public void setVernum(String vernum) {
        this.vernum = vernum == null ? null : vernum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appversion.description
     *
     * @return the value of appversion.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appversion.description
     *
     * @param description the value for appversion.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appversion.updatetime
     *
     * @return the value of appversion.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appversion.updatetime
     *
     * @param updatetime the value for appversion.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appversion.appurl
     *
     * @return the value of appversion.appurl
     *
     * @mbggenerated
     */
    public String getAppurl() {
        return appurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appversion.appurl
     *
     * @param appurl the value for appversion.appurl
     *
     * @mbggenerated
     */
    public void setAppurl(String appurl) {
        this.appurl = appurl == null ? null : appurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appversion.devicetype
     *
     * @return the value of appversion.devicetype
     *
     * @mbggenerated
     */
    public String getDevicetype() {
        return devicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appversion.devicetype
     *
     * @param devicetype the value for appversion.devicetype
     *
     * @mbggenerated
     */
    public void setDevicetype(String devicetype) {
        this.devicetype = devicetype == null ? null : devicetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appversion.isreview
     *
     * @return the value of appversion.isreview
     *
     * @mbggenerated
     */
    public String getIsreview() {
        return isreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appversion.isreview
     *
     * @param isreview the value for appversion.isreview
     *
     * @mbggenerated
     */
    public void setIsreview(String isreview) {
        this.isreview = isreview == null ? null : isreview.trim();
    }
}