package com.cpf.beans.system;

public class RelNewsView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_news_view.viewid
     *
     * @mbggenerated
     */
    private String viewid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_news_view.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_news_view.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_news_view.newsid
     *
     * @mbggenerated
     */
    private String newsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_news_view.viewid
     *
     * @return the value of rel_news_view.viewid
     *
     * @mbggenerated
     */
    public String getViewid() {
        return viewid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_news_view.viewid
     *
     * @param viewid the value for rel_news_view.viewid
     *
     * @mbggenerated
     */
    public void setViewid(String viewid) {
        this.viewid = viewid == null ? null : viewid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_news_view.userid
     *
     * @return the value of rel_news_view.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_news_view.userid
     *
     * @param userid the value for rel_news_view.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_news_view.state
     *
     * @return the value of rel_news_view.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_news_view.state
     *
     * @param state the value for rel_news_view.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_news_view.newsid
     *
     * @return the value of rel_news_view.newsid
     *
     * @mbggenerated
     */
    public String getNewsid() {
        return newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_news_view.newsid
     *
     * @param newsid the value for rel_news_view.newsid
     *
     * @mbggenerated
     */
    public void setNewsid(String newsid) {
        this.newsid = newsid == null ? null : newsid.trim();
    }
}