package com.cpf.beans.system;

public class RelQuestionAnswer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_question_answer.answerid
     *
     * @mbggenerated
     */
    private String answerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_question_answer.questionid
     *
     * @mbggenerated
     */
    private String questionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_question_answer.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_question_answer.answer
     *
     * @mbggenerated
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_question_answer.answerid
     *
     * @return the value of rel_question_answer.answerid
     *
     * @mbggenerated
     */
    public String getAnswerid() {
        return answerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_question_answer.answerid
     *
     * @param answerid the value for rel_question_answer.answerid
     *
     * @mbggenerated
     */
    public void setAnswerid(String answerid) {
        this.answerid = answerid == null ? null : answerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_question_answer.questionid
     *
     * @return the value of rel_question_answer.questionid
     *
     * @mbggenerated
     */
    public String getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_question_answer.questionid
     *
     * @param questionid the value for rel_question_answer.questionid
     *
     * @mbggenerated
     */
    public void setQuestionid(String questionid) {
        this.questionid = questionid == null ? null : questionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_question_answer.userid
     *
     * @return the value of rel_question_answer.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_question_answer.userid
     *
     * @param userid the value for rel_question_answer.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_question_answer.answer
     *
     * @return the value of rel_question_answer.answer
     *
     * @mbggenerated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_question_answer.answer
     *
     * @param answer the value for rel_question_answer.answer
     *
     * @mbggenerated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}