package com.cpf.beans.system;

import java.util.Date;

public class SysAds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ads.adid
     *
     * @mbggenerated
     */
    private String adid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ads.placementid
     *
     * @mbggenerated
     */
    private String placementid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ads.pics
     *
     * @mbggenerated
     */
    private String pics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ads.begintime
     *
     * @mbggenerated
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ads.endtime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ads.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ads.adid
     *
     * @return the value of sys_ads.adid
     *
     * @mbggenerated
     */
    public String getAdid() {
        return adid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ads.adid
     *
     * @param adid the value for sys_ads.adid
     *
     * @mbggenerated
     */
    public void setAdid(String adid) {
        this.adid = adid == null ? null : adid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ads.placementid
     *
     * @return the value of sys_ads.placementid
     *
     * @mbggenerated
     */
    public String getPlacementid() {
        return placementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ads.placementid
     *
     * @param placementid the value for sys_ads.placementid
     *
     * @mbggenerated
     */
    public void setPlacementid(String placementid) {
        this.placementid = placementid == null ? null : placementid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ads.pics
     *
     * @return the value of sys_ads.pics
     *
     * @mbggenerated
     */
    public String getPics() {
        return pics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ads.pics
     *
     * @param pics the value for sys_ads.pics
     *
     * @mbggenerated
     */
    public void setPics(String pics) {
        this.pics = pics == null ? null : pics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ads.begintime
     *
     * @return the value of sys_ads.begintime
     *
     * @mbggenerated
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ads.begintime
     *
     * @param begintime the value for sys_ads.begintime
     *
     * @mbggenerated
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ads.endtime
     *
     * @return the value of sys_ads.endtime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ads.endtime
     *
     * @param endtime the value for sys_ads.endtime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ads.state
     *
     * @return the value of sys_ads.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ads.state
     *
     * @param state the value for sys_ads.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}