package com.cpf.beans.system;

public class SysAdplacement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_adplacement.placementid
     *
     * @mbggenerated
     */
    private String placementid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_adplacement.locationname
     *
     * @mbggenerated
     */
    private String locationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_adplacement.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_adplacement.longl
     *
     * @mbggenerated
     */
    private String longl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_adplacement.width
     *
     * @mbggenerated
     */
    private String width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_adplacement.费用
     *
     * @mbggenerated
     */
    private Double 费用;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_adplacement.placementid
     *
     * @return the value of sys_adplacement.placementid
     *
     * @mbggenerated
     */
    public String getPlacementid() {
        return placementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_adplacement.placementid
     *
     * @param placementid the value for sys_adplacement.placementid
     *
     * @mbggenerated
     */
    public void setPlacementid(String placementid) {
        this.placementid = placementid == null ? null : placementid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_adplacement.locationname
     *
     * @return the value of sys_adplacement.locationname
     *
     * @mbggenerated
     */
    public String getLocationname() {
        return locationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_adplacement.locationname
     *
     * @param locationname the value for sys_adplacement.locationname
     *
     * @mbggenerated
     */
    public void setLocationname(String locationname) {
        this.locationname = locationname == null ? null : locationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_adplacement.state
     *
     * @return the value of sys_adplacement.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_adplacement.state
     *
     * @param state the value for sys_adplacement.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_adplacement.longl
     *
     * @return the value of sys_adplacement.longl
     *
     * @mbggenerated
     */
    public String getLongl() {
        return longl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_adplacement.longl
     *
     * @param longl the value for sys_adplacement.longl
     *
     * @mbggenerated
     */
    public void setLongl(String longl) {
        this.longl = longl == null ? null : longl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_adplacement.width
     *
     * @return the value of sys_adplacement.width
     *
     * @mbggenerated
     */
    public String getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_adplacement.width
     *
     * @param width the value for sys_adplacement.width
     *
     * @mbggenerated
     */
    public void setWidth(String width) {
        this.width = width == null ? null : width.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_adplacement.费用
     *
     * @return the value of sys_adplacement.费用
     *
     * @mbggenerated
     */
    public Double get费用() {
        return 费用;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_adplacement.费用
     *
     * @param 费用 the value for sys_adplacement.费用
     *
     * @mbggenerated
     */
    public void set费用(Double 费用) {
        this.费用 = 费用;
    }
}