package com.cpf.beans.system;

import java.util.Date;

public class SysNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news.newsid
     *
     * @mbggenerated
     */
    private String newsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news.消息内容
     *
     * @mbggenerated
     */
    private String 消息内容;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_news.推送时间
     *
     * @mbggenerated
     */
    private Date 推送时间;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news.newsid
     *
     * @return the value of sys_news.newsid
     *
     * @mbggenerated
     */
    public String getNewsid() {
        return newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news.newsid
     *
     * @param newsid the value for sys_news.newsid
     *
     * @mbggenerated
     */
    public void setNewsid(String newsid) {
        this.newsid = newsid == null ? null : newsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news.消息内容
     *
     * @return the value of sys_news.消息内容
     *
     * @mbggenerated
     */
    public String get消息内容() {
        return 消息内容;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news.消息内容
     *
     * @param 消息内容 the value for sys_news.消息内容
     *
     * @mbggenerated
     */
    public void set消息内容(String 消息内容) {
        this.消息内容 = 消息内容 == null ? null : 消息内容.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_news.推送时间
     *
     * @return the value of sys_news.推送时间
     *
     * @mbggenerated
     */
    public Date get推送时间() {
        return 推送时间;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_news.推送时间
     *
     * @param 推送时间 the value for sys_news.推送时间
     *
     * @mbggenerated
     */
    public void set推送时间(Date 推送时间) {
        this.推送时间 = 推送时间;
    }
}