package com.cpf.beans.system;

public class SysSecurityquestion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_securityquestion.questionid
     *
     * @mbggenerated
     */
    private String questionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_securityquestion.answerid
     *
     * @mbggenerated
     */
    private String answerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_securityquestion.question
     *
     * @mbggenerated
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_securityquestion.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_securityquestion.questionid
     *
     * @return the value of sys_securityquestion.questionid
     *
     * @mbggenerated
     */
    public String getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_securityquestion.questionid
     *
     * @param questionid the value for sys_securityquestion.questionid
     *
     * @mbggenerated
     */
    public void setQuestionid(String questionid) {
        this.questionid = questionid == null ? null : questionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_securityquestion.answerid
     *
     * @return the value of sys_securityquestion.answerid
     *
     * @mbggenerated
     */
    public String getAnswerid() {
        return answerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_securityquestion.answerid
     *
     * @param answerid the value for sys_securityquestion.answerid
     *
     * @mbggenerated
     */
    public void setAnswerid(String answerid) {
        this.answerid = answerid == null ? null : answerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_securityquestion.question
     *
     * @return the value of sys_securityquestion.question
     *
     * @mbggenerated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_securityquestion.question
     *
     * @param question the value for sys_securityquestion.question
     *
     * @mbggenerated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_securityquestion.state
     *
     * @return the value of sys_securityquestion.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_securityquestion.state
     *
     * @param state the value for sys_securityquestion.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}