package com.cpf.beans.system;

public class SysTagsdictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_tagsdictionary.labelid
     *
     * @mbggenerated
     */
    private String labelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_tagsdictionary.labelname
     *
     * @mbggenerated
     */
    private String labelname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_tagsdictionary.labelid
     *
     * @return the value of sys_tagsdictionary.labelid
     *
     * @mbggenerated
     */
    public String getLabelid() {
        return labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_tagsdictionary.labelid
     *
     * @param labelid the value for sys_tagsdictionary.labelid
     *
     * @mbggenerated
     */
    public void setLabelid(String labelid) {
        this.labelid = labelid == null ? null : labelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_tagsdictionary.labelname
     *
     * @return the value of sys_tagsdictionary.labelname
     *
     * @mbggenerated
     */
    public String getLabelname() {
        return labelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_tagsdictionary.labelname
     *
     * @param labelname the value for sys_tagsdictionary.labelname
     *
     * @mbggenerated
     */
    public void setLabelname(String labelname) {
        this.labelname = labelname == null ? null : labelname.trim();
    }
}