package com.cpf.beans.system;

public class SysUserrule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userrule.ruleid
     *
     * @mbggenerated
     */
    private String ruleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userrule.userlevel
     *
     * @mbggenerated
     */
    private String userlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userrule.Features
     *
     * @mbggenerated
     */
    private String features;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userrule.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userrule.ruleid
     *
     * @return the value of sys_userrule.ruleid
     *
     * @mbggenerated
     */
    public String getRuleid() {
        return ruleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userrule.ruleid
     *
     * @param ruleid the value for sys_userrule.ruleid
     *
     * @mbggenerated
     */
    public void setRuleid(String ruleid) {
        this.ruleid = ruleid == null ? null : ruleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userrule.userlevel
     *
     * @return the value of sys_userrule.userlevel
     *
     * @mbggenerated
     */
    public String getUserlevel() {
        return userlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userrule.userlevel
     *
     * @param userlevel the value for sys_userrule.userlevel
     *
     * @mbggenerated
     */
    public void setUserlevel(String userlevel) {
        this.userlevel = userlevel == null ? null : userlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userrule.Features
     *
     * @return the value of sys_userrule.Features
     *
     * @mbggenerated
     */
    public String getFeatures() {
        return features;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userrule.Features
     *
     * @param features the value for sys_userrule.Features
     *
     * @mbggenerated
     */
    public void setFeatures(String features) {
        this.features = features == null ? null : features.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userrule.value
     *
     * @return the value of sys_userrule.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userrule.value
     *
     * @param value the value for sys_userrule.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}