package com.cpf.beans.system;

import java.util.Date;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userinfoid
     *
     * @mbggenerated
     */
    private String userinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.storename
     *
     * @mbggenerated
     */
    private String storename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.photourl
     *
     * @mbggenerated
     */
    private String photourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.introductions
     *
     * @mbggenerated
     */
    private String introductions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.cityid
     *
     * @mbggenerated
     */
    private String cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.graduatedschool
     *
     * @mbggenerated
     */
    private String graduatedschool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.webaddr
     *
     * @mbggenerated
     */
    private String webaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.exhibition
     *
     * @mbggenerated
     */
    private String exhibition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Awards
     *
     * @mbggenerated
     */
    private String awards;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.publishing
     *
     * @mbggenerated
     */
    private String publishing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.cypublished
     *
     * @mbggenerated
     */
    private String cypublished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Verified
     *
     * @mbggenerated
     */
    private String verified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Agencycertification
     *
     * @mbggenerated
     */
    private String agencycertification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.creditlevel
     *
     * @mbggenerated
     */
    private String creditlevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userid
     *
     * @return the value of userinfo.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userid
     *
     * @param userid the value for userinfo.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userinfoid
     *
     * @return the value of userinfo.userinfoid
     *
     * @mbggenerated
     */
    public String getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userinfoid
     *
     * @param userinfoid the value for userinfo.userinfoid
     *
     * @mbggenerated
     */
    public void setUserinfoid(String userinfoid) {
        this.userinfoid = userinfoid == null ? null : userinfoid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.storename
     *
     * @return the value of userinfo.storename
     *
     * @mbggenerated
     */
    public String getStorename() {
        return storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.storename
     *
     * @param storename the value for userinfo.storename
     *
     * @mbggenerated
     */
    public void setStorename(String storename) {
        this.storename = storename == null ? null : storename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.photourl
     *
     * @return the value of userinfo.photourl
     *
     * @mbggenerated
     */
    public String getPhotourl() {
        return photourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.photourl
     *
     * @param photourl the value for userinfo.photourl
     *
     * @mbggenerated
     */
    public void setPhotourl(String photourl) {
        this.photourl = photourl == null ? null : photourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.realname
     *
     * @return the value of userinfo.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.realname
     *
     * @param realname the value for userinfo.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.introductions
     *
     * @return the value of userinfo.introductions
     *
     * @mbggenerated
     */
    public String getIntroductions() {
        return introductions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.introductions
     *
     * @param introductions the value for userinfo.introductions
     *
     * @mbggenerated
     */
    public void setIntroductions(String introductions) {
        this.introductions = introductions == null ? null : introductions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.sex
     *
     * @return the value of userinfo.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.sex
     *
     * @param sex the value for userinfo.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.birthday
     *
     * @return the value of userinfo.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.birthday
     *
     * @param birthday the value for userinfo.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.cityid
     *
     * @return the value of userinfo.cityid
     *
     * @mbggenerated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.cityid
     *
     * @param cityid the value for userinfo.cityid
     *
     * @mbggenerated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.address
     *
     * @return the value of userinfo.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.address
     *
     * @param address the value for userinfo.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.graduatedschool
     *
     * @return the value of userinfo.graduatedschool
     *
     * @mbggenerated
     */
    public String getGraduatedschool() {
        return graduatedschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.graduatedschool
     *
     * @param graduatedschool the value for userinfo.graduatedschool
     *
     * @mbggenerated
     */
    public void setGraduatedschool(String graduatedschool) {
        this.graduatedschool = graduatedschool == null ? null : graduatedschool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.email
     *
     * @return the value of userinfo.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.email
     *
     * @param email the value for userinfo.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.webaddr
     *
     * @return the value of userinfo.webaddr
     *
     * @mbggenerated
     */
    public String getWebaddr() {
        return webaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.webaddr
     *
     * @param webaddr the value for userinfo.webaddr
     *
     * @mbggenerated
     */
    public void setWebaddr(String webaddr) {
        this.webaddr = webaddr == null ? null : webaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.position
     *
     * @return the value of userinfo.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.position
     *
     * @param position the value for userinfo.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.exhibition
     *
     * @return the value of userinfo.exhibition
     *
     * @mbggenerated
     */
    public String getExhibition() {
        return exhibition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.exhibition
     *
     * @param exhibition the value for userinfo.exhibition
     *
     * @mbggenerated
     */
    public void setExhibition(String exhibition) {
        this.exhibition = exhibition == null ? null : exhibition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Awards
     *
     * @return the value of userinfo.Awards
     *
     * @mbggenerated
     */
    public String getAwards() {
        return awards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Awards
     *
     * @param awards the value for userinfo.Awards
     *
     * @mbggenerated
     */
    public void setAwards(String awards) {
        this.awards = awards == null ? null : awards.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.publishing
     *
     * @return the value of userinfo.publishing
     *
     * @mbggenerated
     */
    public String getPublishing() {
        return publishing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.publishing
     *
     * @param publishing the value for userinfo.publishing
     *
     * @mbggenerated
     */
    public void setPublishing(String publishing) {
        this.publishing = publishing == null ? null : publishing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.cypublished
     *
     * @return the value of userinfo.cypublished
     *
     * @mbggenerated
     */
    public String getCypublished() {
        return cypublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.cypublished
     *
     * @param cypublished the value for userinfo.cypublished
     *
     * @mbggenerated
     */
    public void setCypublished(String cypublished) {
        this.cypublished = cypublished == null ? null : cypublished.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Verified
     *
     * @return the value of userinfo.Verified
     *
     * @mbggenerated
     */
    public String getVerified() {
        return verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Verified
     *
     * @param verified the value for userinfo.Verified
     *
     * @mbggenerated
     */
    public void setVerified(String verified) {
        this.verified = verified == null ? null : verified.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Agencycertification
     *
     * @return the value of userinfo.Agencycertification
     *
     * @mbggenerated
     */
    public String getAgencycertification() {
        return agencycertification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Agencycertification
     *
     * @param agencycertification the value for userinfo.Agencycertification
     *
     * @mbggenerated
     */
    public void setAgencycertification(String agencycertification) {
        this.agencycertification = agencycertification == null ? null : agencycertification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.creditlevel
     *
     * @return the value of userinfo.creditlevel
     *
     * @mbggenerated
     */
    public String getCreditlevel() {
        return creditlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.creditlevel
     *
     * @param creditlevel the value for userinfo.creditlevel
     *
     * @mbggenerated
     */
    public void setCreditlevel(String creditlevel) {
        this.creditlevel = creditlevel == null ? null : creditlevel.trim();
    }
}