package com.cpf.beans.system;

import java.util.Date;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.phonenum
     *
     * @mbggenerated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.isonline
     *
     * @mbggenerated
     */
    private String isonline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.lastloginintime
     *
     * @mbggenerated
     */
    private Date lastloginintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.usertype
     *
     * @mbggenerated
     */
    private String usertype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.userid
     *
     * @return the value of users.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.userid
     *
     * @param userid the value for users.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.phonenum
     *
     * @return the value of users.phonenum
     *
     * @mbggenerated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.phonenum
     *
     * @param phonenum the value for users.phonenum
     *
     * @mbggenerated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.isonline
     *
     * @return the value of users.isonline
     *
     * @mbggenerated
     */
    public String getIsonline() {
        return isonline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.isonline
     *
     * @param isonline the value for users.isonline
     *
     * @mbggenerated
     */
    public void setIsonline(String isonline) {
        this.isonline = isonline == null ? null : isonline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.createtime
     *
     * @return the value of users.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.createtime
     *
     * @param createtime the value for users.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.lastloginintime
     *
     * @return the value of users.lastloginintime
     *
     * @mbggenerated
     */
    public Date getLastloginintime() {
        return lastloginintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.lastloginintime
     *
     * @param lastloginintime the value for users.lastloginintime
     *
     * @mbggenerated
     */
    public void setLastloginintime(Date lastloginintime) {
        this.lastloginintime = lastloginintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ip
     *
     * @return the value of users.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.ip
     *
     * @param ip the value for users.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.state
     *
     * @return the value of users.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.state
     *
     * @param state the value for users.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.usertype
     *
     * @return the value of users.usertype
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.usertype
     *
     * @param usertype the value for users.usertype
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }
}