package com.cpf.beans.system;

import java.util.Date;

public class Useramount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useramount.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useramount.amountid
     *
     * @mbggenerated
     */
    private String amountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useramount.Balance
     *
     * @mbggenerated
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useramount.AvailableBalance
     *
     * @mbggenerated
     */
    private Double availablebalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useramount.Margin
     *
     * @mbggenerated
     */
    private Double margin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useramount.isMargin
     *
     * @mbggenerated
     */
    private String ismargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useramount.kymargin
     *
     * @mbggenerated
     */
    private Double kymargin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useramount.会员等级
     *
     * @mbggenerated
     */
    private String 会员等级;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useramount.会员到期时间
     *
     * @mbggenerated
     */
    private Date 会员到期时间;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useramount.userid
     *
     * @return the value of useramount.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useramount.userid
     *
     * @param userid the value for useramount.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useramount.amountid
     *
     * @return the value of useramount.amountid
     *
     * @mbggenerated
     */
    public String getAmountid() {
        return amountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useramount.amountid
     *
     * @param amountid the value for useramount.amountid
     *
     * @mbggenerated
     */
    public void setAmountid(String amountid) {
        this.amountid = amountid == null ? null : amountid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useramount.Balance
     *
     * @return the value of useramount.Balance
     *
     * @mbggenerated
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useramount.Balance
     *
     * @param balance the value for useramount.Balance
     *
     * @mbggenerated
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useramount.AvailableBalance
     *
     * @return the value of useramount.AvailableBalance
     *
     * @mbggenerated
     */
    public Double getAvailablebalance() {
        return availablebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useramount.AvailableBalance
     *
     * @param availablebalance the value for useramount.AvailableBalance
     *
     * @mbggenerated
     */
    public void setAvailablebalance(Double availablebalance) {
        this.availablebalance = availablebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useramount.Margin
     *
     * @return the value of useramount.Margin
     *
     * @mbggenerated
     */
    public Double getMargin() {
        return margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useramount.Margin
     *
     * @param margin the value for useramount.Margin
     *
     * @mbggenerated
     */
    public void setMargin(Double margin) {
        this.margin = margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useramount.isMargin
     *
     * @return the value of useramount.isMargin
     *
     * @mbggenerated
     */
    public String getIsmargin() {
        return ismargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useramount.isMargin
     *
     * @param ismargin the value for useramount.isMargin
     *
     * @mbggenerated
     */
    public void setIsmargin(String ismargin) {
        this.ismargin = ismargin == null ? null : ismargin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useramount.kymargin
     *
     * @return the value of useramount.kymargin
     *
     * @mbggenerated
     */
    public Double getKymargin() {
        return kymargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useramount.kymargin
     *
     * @param kymargin the value for useramount.kymargin
     *
     * @mbggenerated
     */
    public void setKymargin(Double kymargin) {
        this.kymargin = kymargin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useramount.会员等级
     *
     * @return the value of useramount.会员等级
     *
     * @mbggenerated
     */
    public String get会员等级() {
        return 会员等级;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useramount.会员等级
     *
     * @param 会员等级 the value for useramount.会员等级
     *
     * @mbggenerated
     */
    public void set会员等级(String 会员等级) {
        this.会员等级 = 会员等级 == null ? null : 会员等级.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useramount.会员到期时间
     *
     * @return the value of useramount.会员到期时间
     *
     * @mbggenerated
     */
    public Date get会员到期时间() {
        return 会员到期时间;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useramount.会员到期时间
     *
     * @param 会员到期时间 the value for useramount.会员到期时间
     *
     * @mbggenerated
     */
    public void set会员到期时间(Date 会员到期时间) {
        this.会员到期时间 = 会员到期时间;
    }
}