package com.cpf.beans.transaction;

import java.util.Date;

public class TraBarters {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.Barorderid
     *
     * @mbggenerated
     */
    private String barorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.ordercode
     *
     * @mbggenerated
     */
    private String ordercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.sponsorid
     *
     * @mbggenerated
     */
    private String sponsorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.Recipientid
     *
     * @mbggenerated
     */
    private String recipientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.sponsorbzj
     *
     * @mbggenerated
     */
    private Double sponsorbzj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.Recipientbzj
     *
     * @mbggenerated
     */
    private Double recipientbzj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.issponsorLogistics
     *
     * @mbggenerated
     */
    private String issponsorlogistics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.isRecipientLogistics
     *
     * @mbggenerated
     */
    private String isrecipientlogistics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.sponsorname
     *
     * @mbggenerated
     */
    private String sponsorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.sponsorphone
     *
     * @mbggenerated
     */
    private String sponsorphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.sponsoraddress
     *
     * @mbggenerated
     */
    private String sponsoraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.sponsorkdgs
     *
     * @mbggenerated
     */
    private String sponsorkdgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.sponsorkddh
     *
     * @mbggenerated
     */
    private String sponsorkddh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.sponsorkdtime
     *
     * @mbggenerated
     */
    private Date sponsorkdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.Recipientname
     *
     * @mbggenerated
     */
    private String recipientname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.Recipientphone
     *
     * @mbggenerated
     */
    private String recipientphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.Recipientaddress
     *
     * @mbggenerated
     */
    private String recipientaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.Recipientkdgs
     *
     * @mbggenerated
     */
    private String recipientkdgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.Recipientkddh
     *
     * @mbggenerated
     */
    private String recipientkddh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_barters.Recipientkdtime
     *
     * @mbggenerated
     */
    private Date recipientkdtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.Barorderid
     *
     * @return the value of tra_barters.Barorderid
     *
     * @mbggenerated
     */
    public String getBarorderid() {
        return barorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.Barorderid
     *
     * @param barorderid the value for tra_barters.Barorderid
     *
     * @mbggenerated
     */
    public void setBarorderid(String barorderid) {
        this.barorderid = barorderid == null ? null : barorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.createtime
     *
     * @return the value of tra_barters.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.createtime
     *
     * @param createtime the value for tra_barters.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.ordercode
     *
     * @return the value of tra_barters.ordercode
     *
     * @mbggenerated
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.ordercode
     *
     * @param ordercode the value for tra_barters.ordercode
     *
     * @mbggenerated
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode == null ? null : ordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.sponsorid
     *
     * @return the value of tra_barters.sponsorid
     *
     * @mbggenerated
     */
    public String getSponsorid() {
        return sponsorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.sponsorid
     *
     * @param sponsorid the value for tra_barters.sponsorid
     *
     * @mbggenerated
     */
    public void setSponsorid(String sponsorid) {
        this.sponsorid = sponsorid == null ? null : sponsorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.Recipientid
     *
     * @return the value of tra_barters.Recipientid
     *
     * @mbggenerated
     */
    public String getRecipientid() {
        return recipientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.Recipientid
     *
     * @param recipientid the value for tra_barters.Recipientid
     *
     * @mbggenerated
     */
    public void setRecipientid(String recipientid) {
        this.recipientid = recipientid == null ? null : recipientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.sponsorbzj
     *
     * @return the value of tra_barters.sponsorbzj
     *
     * @mbggenerated
     */
    public Double getSponsorbzj() {
        return sponsorbzj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.sponsorbzj
     *
     * @param sponsorbzj the value for tra_barters.sponsorbzj
     *
     * @mbggenerated
     */
    public void setSponsorbzj(Double sponsorbzj) {
        this.sponsorbzj = sponsorbzj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.Recipientbzj
     *
     * @return the value of tra_barters.Recipientbzj
     *
     * @mbggenerated
     */
    public Double getRecipientbzj() {
        return recipientbzj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.Recipientbzj
     *
     * @param recipientbzj the value for tra_barters.Recipientbzj
     *
     * @mbggenerated
     */
    public void setRecipientbzj(Double recipientbzj) {
        this.recipientbzj = recipientbzj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.state
     *
     * @return the value of tra_barters.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.state
     *
     * @param state the value for tra_barters.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.issponsorLogistics
     *
     * @return the value of tra_barters.issponsorLogistics
     *
     * @mbggenerated
     */
    public String getIssponsorlogistics() {
        return issponsorlogistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.issponsorLogistics
     *
     * @param issponsorlogistics the value for tra_barters.issponsorLogistics
     *
     * @mbggenerated
     */
    public void setIssponsorlogistics(String issponsorlogistics) {
        this.issponsorlogistics = issponsorlogistics == null ? null : issponsorlogistics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.isRecipientLogistics
     *
     * @return the value of tra_barters.isRecipientLogistics
     *
     * @mbggenerated
     */
    public String getIsrecipientlogistics() {
        return isrecipientlogistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.isRecipientLogistics
     *
     * @param isrecipientlogistics the value for tra_barters.isRecipientLogistics
     *
     * @mbggenerated
     */
    public void setIsrecipientlogistics(String isrecipientlogistics) {
        this.isrecipientlogistics = isrecipientlogistics == null ? null : isrecipientlogistics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.sponsorname
     *
     * @return the value of tra_barters.sponsorname
     *
     * @mbggenerated
     */
    public String getSponsorname() {
        return sponsorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.sponsorname
     *
     * @param sponsorname the value for tra_barters.sponsorname
     *
     * @mbggenerated
     */
    public void setSponsorname(String sponsorname) {
        this.sponsorname = sponsorname == null ? null : sponsorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.sponsorphone
     *
     * @return the value of tra_barters.sponsorphone
     *
     * @mbggenerated
     */
    public String getSponsorphone() {
        return sponsorphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.sponsorphone
     *
     * @param sponsorphone the value for tra_barters.sponsorphone
     *
     * @mbggenerated
     */
    public void setSponsorphone(String sponsorphone) {
        this.sponsorphone = sponsorphone == null ? null : sponsorphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.sponsoraddress
     *
     * @return the value of tra_barters.sponsoraddress
     *
     * @mbggenerated
     */
    public String getSponsoraddress() {
        return sponsoraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.sponsoraddress
     *
     * @param sponsoraddress the value for tra_barters.sponsoraddress
     *
     * @mbggenerated
     */
    public void setSponsoraddress(String sponsoraddress) {
        this.sponsoraddress = sponsoraddress == null ? null : sponsoraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.sponsorkdgs
     *
     * @return the value of tra_barters.sponsorkdgs
     *
     * @mbggenerated
     */
    public String getSponsorkdgs() {
        return sponsorkdgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.sponsorkdgs
     *
     * @param sponsorkdgs the value for tra_barters.sponsorkdgs
     *
     * @mbggenerated
     */
    public void setSponsorkdgs(String sponsorkdgs) {
        this.sponsorkdgs = sponsorkdgs == null ? null : sponsorkdgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.sponsorkddh
     *
     * @return the value of tra_barters.sponsorkddh
     *
     * @mbggenerated
     */
    public String getSponsorkddh() {
        return sponsorkddh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.sponsorkddh
     *
     * @param sponsorkddh the value for tra_barters.sponsorkddh
     *
     * @mbggenerated
     */
    public void setSponsorkddh(String sponsorkddh) {
        this.sponsorkddh = sponsorkddh == null ? null : sponsorkddh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.sponsorkdtime
     *
     * @return the value of tra_barters.sponsorkdtime
     *
     * @mbggenerated
     */
    public Date getSponsorkdtime() {
        return sponsorkdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.sponsorkdtime
     *
     * @param sponsorkdtime the value for tra_barters.sponsorkdtime
     *
     * @mbggenerated
     */
    public void setSponsorkdtime(Date sponsorkdtime) {
        this.sponsorkdtime = sponsorkdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.Recipientname
     *
     * @return the value of tra_barters.Recipientname
     *
     * @mbggenerated
     */
    public String getRecipientname() {
        return recipientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.Recipientname
     *
     * @param recipientname the value for tra_barters.Recipientname
     *
     * @mbggenerated
     */
    public void setRecipientname(String recipientname) {
        this.recipientname = recipientname == null ? null : recipientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.Recipientphone
     *
     * @return the value of tra_barters.Recipientphone
     *
     * @mbggenerated
     */
    public String getRecipientphone() {
        return recipientphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.Recipientphone
     *
     * @param recipientphone the value for tra_barters.Recipientphone
     *
     * @mbggenerated
     */
    public void setRecipientphone(String recipientphone) {
        this.recipientphone = recipientphone == null ? null : recipientphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.Recipientaddress
     *
     * @return the value of tra_barters.Recipientaddress
     *
     * @mbggenerated
     */
    public String getRecipientaddress() {
        return recipientaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.Recipientaddress
     *
     * @param recipientaddress the value for tra_barters.Recipientaddress
     *
     * @mbggenerated
     */
    public void setRecipientaddress(String recipientaddress) {
        this.recipientaddress = recipientaddress == null ? null : recipientaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.Recipientkdgs
     *
     * @return the value of tra_barters.Recipientkdgs
     *
     * @mbggenerated
     */
    public String getRecipientkdgs() {
        return recipientkdgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.Recipientkdgs
     *
     * @param recipientkdgs the value for tra_barters.Recipientkdgs
     *
     * @mbggenerated
     */
    public void setRecipientkdgs(String recipientkdgs) {
        this.recipientkdgs = recipientkdgs == null ? null : recipientkdgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.Recipientkddh
     *
     * @return the value of tra_barters.Recipientkddh
     *
     * @mbggenerated
     */
    public String getRecipientkddh() {
        return recipientkddh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.Recipientkddh
     *
     * @param recipientkddh the value for tra_barters.Recipientkddh
     *
     * @mbggenerated
     */
    public void setRecipientkddh(String recipientkddh) {
        this.recipientkddh = recipientkddh == null ? null : recipientkddh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_barters.Recipientkdtime
     *
     * @return the value of tra_barters.Recipientkdtime
     *
     * @mbggenerated
     */
    public Date getRecipientkdtime() {
        return recipientkdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_barters.Recipientkdtime
     *
     * @param recipientkdtime the value for tra_barters.Recipientkdtime
     *
     * @mbggenerated
     */
    public void setRecipientkdtime(Date recipientkdtime) {
        this.recipientkdtime = recipientkdtime;
    }
}