package com.cpf.beans.transaction;

import java.util.Date;

public class TraBidrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_bidrecord.recordid
     *
     * @mbggenerated
     */
    private String recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_bidrecord.Specialid
     *
     * @mbggenerated
     */
    private String specialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_bidrecord.productid
     *
     * @mbggenerated
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_bidrecord.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_bidrecord.pricetime
     *
     * @mbggenerated
     */
    private Date pricetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_bidrecord.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_bidrecord.isdeal
     *
     * @mbggenerated
     */
    private String isdeal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_bidrecord.recordid
     *
     * @return the value of tra_bidrecord.recordid
     *
     * @mbggenerated
     */
    public String getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_bidrecord.recordid
     *
     * @param recordid the value for tra_bidrecord.recordid
     *
     * @mbggenerated
     */
    public void setRecordid(String recordid) {
        this.recordid = recordid == null ? null : recordid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_bidrecord.Specialid
     *
     * @return the value of tra_bidrecord.Specialid
     *
     * @mbggenerated
     */
    public String getSpecialid() {
        return specialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_bidrecord.Specialid
     *
     * @param specialid the value for tra_bidrecord.Specialid
     *
     * @mbggenerated
     */
    public void setSpecialid(String specialid) {
        this.specialid = specialid == null ? null : specialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_bidrecord.productid
     *
     * @return the value of tra_bidrecord.productid
     *
     * @mbggenerated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_bidrecord.productid
     *
     * @param productid the value for tra_bidrecord.productid
     *
     * @mbggenerated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_bidrecord.price
     *
     * @return the value of tra_bidrecord.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_bidrecord.price
     *
     * @param price the value for tra_bidrecord.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_bidrecord.pricetime
     *
     * @return the value of tra_bidrecord.pricetime
     *
     * @mbggenerated
     */
    public Date getPricetime() {
        return pricetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_bidrecord.pricetime
     *
     * @param pricetime the value for tra_bidrecord.pricetime
     *
     * @mbggenerated
     */
    public void setPricetime(Date pricetime) {
        this.pricetime = pricetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_bidrecord.userid
     *
     * @return the value of tra_bidrecord.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_bidrecord.userid
     *
     * @param userid the value for tra_bidrecord.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_bidrecord.isdeal
     *
     * @return the value of tra_bidrecord.isdeal
     *
     * @mbggenerated
     */
    public String getIsdeal() {
        return isdeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_bidrecord.isdeal
     *
     * @param isdeal the value for tra_bidrecord.isdeal
     *
     * @mbggenerated
     */
    public void setIsdeal(String isdeal) {
        this.isdeal = isdeal == null ? null : isdeal.trim();
    }
}