package com.cpf.beans.transaction;

public class TraCategories {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_categories.cateid
     *
     * @mbggenerated
     */
    private String cateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_categories.catename
     *
     * @mbggenerated
     */
    private String catename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_categories.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_categories.catecode
     *
     * @mbggenerated
     */
    private String catecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_categories.cateid
     *
     * @return the value of tra_categories.cateid
     *
     * @mbggenerated
     */
    public String getCateid() {
        return cateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_categories.cateid
     *
     * @param cateid the value for tra_categories.cateid
     *
     * @mbggenerated
     */
    public void setCateid(String cateid) {
        this.cateid = cateid == null ? null : cateid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_categories.catename
     *
     * @return the value of tra_categories.catename
     *
     * @mbggenerated
     */
    public String getCatename() {
        return catename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_categories.catename
     *
     * @param catename the value for tra_categories.catename
     *
     * @mbggenerated
     */
    public void setCatename(String catename) {
        this.catename = catename == null ? null : catename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_categories.state
     *
     * @return the value of tra_categories.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_categories.state
     *
     * @param state the value for tra_categories.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_categories.catecode
     *
     * @return the value of tra_categories.catecode
     *
     * @mbggenerated
     */
    public String getCatecode() {
        return catecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_categories.catecode
     *
     * @param catecode the value for tra_categories.catecode
     *
     * @mbggenerated
     */
    public void setCatecode(String catecode) {
        this.catecode = catecode == null ? null : catecode.trim();
    }
}