package com.cpf.beans.transaction;

import java.util.Date;

public class TraOfficialspecial {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_officialspecial.Officialid
     *
     * @mbggenerated
     */
    private String officialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_officialspecial.Specialname
     *
     * @mbggenerated
     */
    private String specialname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_officialspecial.Specialcover
     *
     * @mbggenerated
     */
    private String specialcover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_officialspecial.Previewbegintimetime
     *
     * @mbggenerated
     */
    private Date previewbegintimetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_officialspecial.Previewendtime
     *
     * @mbggenerated
     */
    private Date previewendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_officialspecial.Auctionbegintime
     *
     * @mbggenerated
     */
    private Date auctionbegintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_officialspecial.Auctionendtime
     *
     * @mbggenerated
     */
    private Date auctionendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_officialspecial.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_officialspecial.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_officialspecial.Officialid
     *
     * @return the value of tra_officialspecial.Officialid
     *
     * @mbggenerated
     */
    public String getOfficialid() {
        return officialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_officialspecial.Officialid
     *
     * @param officialid the value for tra_officialspecial.Officialid
     *
     * @mbggenerated
     */
    public void setOfficialid(String officialid) {
        this.officialid = officialid == null ? null : officialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_officialspecial.Specialname
     *
     * @return the value of tra_officialspecial.Specialname
     *
     * @mbggenerated
     */
    public String getSpecialname() {
        return specialname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_officialspecial.Specialname
     *
     * @param specialname the value for tra_officialspecial.Specialname
     *
     * @mbggenerated
     */
    public void setSpecialname(String specialname) {
        this.specialname = specialname == null ? null : specialname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_officialspecial.Specialcover
     *
     * @return the value of tra_officialspecial.Specialcover
     *
     * @mbggenerated
     */
    public String getSpecialcover() {
        return specialcover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_officialspecial.Specialcover
     *
     * @param specialcover the value for tra_officialspecial.Specialcover
     *
     * @mbggenerated
     */
    public void setSpecialcover(String specialcover) {
        this.specialcover = specialcover == null ? null : specialcover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_officialspecial.Previewbegintimetime
     *
     * @return the value of tra_officialspecial.Previewbegintimetime
     *
     * @mbggenerated
     */
    public Date getPreviewbegintimetime() {
        return previewbegintimetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_officialspecial.Previewbegintimetime
     *
     * @param previewbegintimetime the value for tra_officialspecial.Previewbegintimetime
     *
     * @mbggenerated
     */
    public void setPreviewbegintimetime(Date previewbegintimetime) {
        this.previewbegintimetime = previewbegintimetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_officialspecial.Previewendtime
     *
     * @return the value of tra_officialspecial.Previewendtime
     *
     * @mbggenerated
     */
    public Date getPreviewendtime() {
        return previewendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_officialspecial.Previewendtime
     *
     * @param previewendtime the value for tra_officialspecial.Previewendtime
     *
     * @mbggenerated
     */
    public void setPreviewendtime(Date previewendtime) {
        this.previewendtime = previewendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_officialspecial.Auctionbegintime
     *
     * @return the value of tra_officialspecial.Auctionbegintime
     *
     * @mbggenerated
     */
    public Date getAuctionbegintime() {
        return auctionbegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_officialspecial.Auctionbegintime
     *
     * @param auctionbegintime the value for tra_officialspecial.Auctionbegintime
     *
     * @mbggenerated
     */
    public void setAuctionbegintime(Date auctionbegintime) {
        this.auctionbegintime = auctionbegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_officialspecial.Auctionendtime
     *
     * @return the value of tra_officialspecial.Auctionendtime
     *
     * @mbggenerated
     */
    public Date getAuctionendtime() {
        return auctionendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_officialspecial.Auctionendtime
     *
     * @param auctionendtime the value for tra_officialspecial.Auctionendtime
     *
     * @mbggenerated
     */
    public void setAuctionendtime(Date auctionendtime) {
        this.auctionendtime = auctionendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_officialspecial.state
     *
     * @return the value of tra_officialspecial.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_officialspecial.state
     *
     * @param state the value for tra_officialspecial.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_officialspecial.userid
     *
     * @return the value of tra_officialspecial.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_officialspecial.userid
     *
     * @param userid the value for tra_officialspecial.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}