package com.cpf.beans.transaction;

import java.util.Date;

public class TraProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.productid
     *
     * @mbggenerated
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.productcode
     *
     * @mbggenerated
     */
    private String productcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.productname
     *
     * @mbggenerated
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.cateid
     *
     * @mbggenerated
     */
    private String cateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.isfinished
     *
     * @mbggenerated
     */
    private String isfinished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.defect
     *
     * @mbggenerated
     */
    private String defect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.isOriginal
     *
     * @mbggenerated
     */
    private String isoriginal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.ismyself
     *
     * @mbggenerated
     */
    private String ismyself;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.longl
     *
     * @mbggenerated
     */
    private String longl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.width
     *
     * @mbggenerated
     */
    private String width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.Material
     *
     * @mbggenerated
     */
    private String material;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.Framed
     *
     * @mbggenerated
     */
    private String framed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.shape
     *
     * @mbggenerated
     */
    private String shape;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.era
     *
     * @mbggenerated
     */
    private String era;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.cretime
     *
     * @mbggenerated
     */
    private Date cretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.isMultiple
     *
     * @mbggenerated
     */
    private String ismultiple;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_product.details
     *
     * @mbggenerated
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.productid
     *
     * @return the value of tra_product.productid
     *
     * @mbggenerated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.productid
     *
     * @param productid the value for tra_product.productid
     *
     * @mbggenerated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.productcode
     *
     * @return the value of tra_product.productcode
     *
     * @mbggenerated
     */
    public String getProductcode() {
        return productcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.productcode
     *
     * @param productcode the value for tra_product.productcode
     *
     * @mbggenerated
     */
    public void setProductcode(String productcode) {
        this.productcode = productcode == null ? null : productcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.userid
     *
     * @return the value of tra_product.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.userid
     *
     * @param userid the value for tra_product.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.productname
     *
     * @return the value of tra_product.productname
     *
     * @mbggenerated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.productname
     *
     * @param productname the value for tra_product.productname
     *
     * @mbggenerated
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.author
     *
     * @return the value of tra_product.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.author
     *
     * @param author the value for tra_product.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.cateid
     *
     * @return the value of tra_product.cateid
     *
     * @mbggenerated
     */
    public String getCateid() {
        return cateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.cateid
     *
     * @param cateid the value for tra_product.cateid
     *
     * @mbggenerated
     */
    public void setCateid(String cateid) {
        this.cateid = cateid == null ? null : cateid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.isfinished
     *
     * @return the value of tra_product.isfinished
     *
     * @mbggenerated
     */
    public String getIsfinished() {
        return isfinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.isfinished
     *
     * @param isfinished the value for tra_product.isfinished
     *
     * @mbggenerated
     */
    public void setIsfinished(String isfinished) {
        this.isfinished = isfinished == null ? null : isfinished.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.defect
     *
     * @return the value of tra_product.defect
     *
     * @mbggenerated
     */
    public String getDefect() {
        return defect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.defect
     *
     * @param defect the value for tra_product.defect
     *
     * @mbggenerated
     */
    public void setDefect(String defect) {
        this.defect = defect == null ? null : defect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.isOriginal
     *
     * @return the value of tra_product.isOriginal
     *
     * @mbggenerated
     */
    public String getIsoriginal() {
        return isoriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.isOriginal
     *
     * @param isoriginal the value for tra_product.isOriginal
     *
     * @mbggenerated
     */
    public void setIsoriginal(String isoriginal) {
        this.isoriginal = isoriginal == null ? null : isoriginal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.ismyself
     *
     * @return the value of tra_product.ismyself
     *
     * @mbggenerated
     */
    public String getIsmyself() {
        return ismyself;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.ismyself
     *
     * @param ismyself the value for tra_product.ismyself
     *
     * @mbggenerated
     */
    public void setIsmyself(String ismyself) {
        this.ismyself = ismyself == null ? null : ismyself.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.longl
     *
     * @return the value of tra_product.longl
     *
     * @mbggenerated
     */
    public String getLongl() {
        return longl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.longl
     *
     * @param longl the value for tra_product.longl
     *
     * @mbggenerated
     */
    public void setLongl(String longl) {
        this.longl = longl == null ? null : longl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.width
     *
     * @return the value of tra_product.width
     *
     * @mbggenerated
     */
    public String getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.width
     *
     * @param width the value for tra_product.width
     *
     * @mbggenerated
     */
    public void setWidth(String width) {
        this.width = width == null ? null : width.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.Material
     *
     * @return the value of tra_product.Material
     *
     * @mbggenerated
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.Material
     *
     * @param material the value for tra_product.Material
     *
     * @mbggenerated
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.Framed
     *
     * @return the value of tra_product.Framed
     *
     * @mbggenerated
     */
    public String getFramed() {
        return framed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.Framed
     *
     * @param framed the value for tra_product.Framed
     *
     * @mbggenerated
     */
    public void setFramed(String framed) {
        this.framed = framed == null ? null : framed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.shape
     *
     * @return the value of tra_product.shape
     *
     * @mbggenerated
     */
    public String getShape() {
        return shape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.shape
     *
     * @param shape the value for tra_product.shape
     *
     * @mbggenerated
     */
    public void setShape(String shape) {
        this.shape = shape == null ? null : shape.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.era
     *
     * @return the value of tra_product.era
     *
     * @mbggenerated
     */
    public String getEra() {
        return era;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.era
     *
     * @param era the value for tra_product.era
     *
     * @mbggenerated
     */
    public void setEra(String era) {
        this.era = era == null ? null : era.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.cretime
     *
     * @return the value of tra_product.cretime
     *
     * @mbggenerated
     */
    public Date getCretime() {
        return cretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.cretime
     *
     * @param cretime the value for tra_product.cretime
     *
     * @mbggenerated
     */
    public void setCretime(Date cretime) {
        this.cretime = cretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.state
     *
     * @return the value of tra_product.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.state
     *
     * @param state the value for tra_product.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.isMultiple
     *
     * @return the value of tra_product.isMultiple
     *
     * @mbggenerated
     */
    public String getIsmultiple() {
        return ismultiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.isMultiple
     *
     * @param ismultiple the value for tra_product.isMultiple
     *
     * @mbggenerated
     */
    public void setIsmultiple(String ismultiple) {
        this.ismultiple = ismultiple == null ? null : ismultiple.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_product.details
     *
     * @return the value of tra_product.details
     *
     * @mbggenerated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_product.details
     *
     * @param details the value for tra_product.details
     *
     * @mbggenerated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}