package com.cpf.beans.transaction;

import java.util.Date;

public class TraPersonalspecial {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_personalspecial.Specialid
     *
     * @mbggenerated
     */
    private String specialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_personalspecial.Specialname
     *
     * @mbggenerated
     */
    private String specialname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_personalspecial.Specialcover
     *
     * @mbggenerated
     */
    private String specialcover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_personalspecial.Previewbegintimetime
     *
     * @mbggenerated
     */
    private Date previewbegintimetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_personalspecial.Previewendtime
     *
     * @mbggenerated
     */
    private Date previewendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_personalspecial.Auctionbegintime
     *
     * @mbggenerated
     */
    private Date auctionbegintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_personalspecial.Auctionendtime
     *
     * @mbggenerated
     */
    private Date auctionendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_personalspecial.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_personalspecial.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_personalspecial.isAudit
     *
     * @mbggenerated
     */
    private String isaudit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_personalspecial.Specialid
     *
     * @return the value of tra_personalspecial.Specialid
     *
     * @mbggenerated
     */
    public String getSpecialid() {
        return specialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_personalspecial.Specialid
     *
     * @param specialid the value for tra_personalspecial.Specialid
     *
     * @mbggenerated
     */
    public void setSpecialid(String specialid) {
        this.specialid = specialid == null ? null : specialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_personalspecial.Specialname
     *
     * @return the value of tra_personalspecial.Specialname
     *
     * @mbggenerated
     */
    public String getSpecialname() {
        return specialname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_personalspecial.Specialname
     *
     * @param specialname the value for tra_personalspecial.Specialname
     *
     * @mbggenerated
     */
    public void setSpecialname(String specialname) {
        this.specialname = specialname == null ? null : specialname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_personalspecial.Specialcover
     *
     * @return the value of tra_personalspecial.Specialcover
     *
     * @mbggenerated
     */
    public String getSpecialcover() {
        return specialcover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_personalspecial.Specialcover
     *
     * @param specialcover the value for tra_personalspecial.Specialcover
     *
     * @mbggenerated
     */
    public void setSpecialcover(String specialcover) {
        this.specialcover = specialcover == null ? null : specialcover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_personalspecial.Previewbegintimetime
     *
     * @return the value of tra_personalspecial.Previewbegintimetime
     *
     * @mbggenerated
     */
    public Date getPreviewbegintimetime() {
        return previewbegintimetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_personalspecial.Previewbegintimetime
     *
     * @param previewbegintimetime the value for tra_personalspecial.Previewbegintimetime
     *
     * @mbggenerated
     */
    public void setPreviewbegintimetime(Date previewbegintimetime) {
        this.previewbegintimetime = previewbegintimetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_personalspecial.Previewendtime
     *
     * @return the value of tra_personalspecial.Previewendtime
     *
     * @mbggenerated
     */
    public Date getPreviewendtime() {
        return previewendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_personalspecial.Previewendtime
     *
     * @param previewendtime the value for tra_personalspecial.Previewendtime
     *
     * @mbggenerated
     */
    public void setPreviewendtime(Date previewendtime) {
        this.previewendtime = previewendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_personalspecial.Auctionbegintime
     *
     * @return the value of tra_personalspecial.Auctionbegintime
     *
     * @mbggenerated
     */
    public Date getAuctionbegintime() {
        return auctionbegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_personalspecial.Auctionbegintime
     *
     * @param auctionbegintime the value for tra_personalspecial.Auctionbegintime
     *
     * @mbggenerated
     */
    public void setAuctionbegintime(Date auctionbegintime) {
        this.auctionbegintime = auctionbegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_personalspecial.Auctionendtime
     *
     * @return the value of tra_personalspecial.Auctionendtime
     *
     * @mbggenerated
     */
    public Date getAuctionendtime() {
        return auctionendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_personalspecial.Auctionendtime
     *
     * @param auctionendtime the value for tra_personalspecial.Auctionendtime
     *
     * @mbggenerated
     */
    public void setAuctionendtime(Date auctionendtime) {
        this.auctionendtime = auctionendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_personalspecial.state
     *
     * @return the value of tra_personalspecial.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_personalspecial.state
     *
     * @param state the value for tra_personalspecial.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_personalspecial.userid
     *
     * @return the value of tra_personalspecial.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_personalspecial.userid
     *
     * @param userid the value for tra_personalspecial.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_personalspecial.isAudit
     *
     * @return the value of tra_personalspecial.isAudit
     *
     * @mbggenerated
     */
    public String getIsaudit() {
        return isaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_personalspecial.isAudit
     *
     * @param isaudit the value for tra_personalspecial.isAudit
     *
     * @mbggenerated
     */
    public void setIsaudit(String isaudit) {
        this.isaudit = isaudit == null ? null : isaudit.trim();
    }
}