package com.cpf.beans.transaction;

import java.util.Date;

public class TraRechargerecords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_rechargerecords.Rechargid
     *
     * @mbggenerated
     */
    private String rechargid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_rechargerecords.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_rechargerecords.amount
     *
     * @mbggenerated
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_rechargerecords.cretime
     *
     * @mbggenerated
     */
    private Date cretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_rechargerecords.paytype
     *
     * @mbggenerated
     */
    private String paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_rechargerecords.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_rechargerecords.Rechargid
     *
     * @return the value of tra_rechargerecords.Rechargid
     *
     * @mbggenerated
     */
    public String getRechargid() {
        return rechargid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_rechargerecords.Rechargid
     *
     * @param rechargid the value for tra_rechargerecords.Rechargid
     *
     * @mbggenerated
     */
    public void setRechargid(String rechargid) {
        this.rechargid = rechargid == null ? null : rechargid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_rechargerecords.userid
     *
     * @return the value of tra_rechargerecords.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_rechargerecords.userid
     *
     * @param userid the value for tra_rechargerecords.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_rechargerecords.amount
     *
     * @return the value of tra_rechargerecords.amount
     *
     * @mbggenerated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_rechargerecords.amount
     *
     * @param amount the value for tra_rechargerecords.amount
     *
     * @mbggenerated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_rechargerecords.cretime
     *
     * @return the value of tra_rechargerecords.cretime
     *
     * @mbggenerated
     */
    public Date getCretime() {
        return cretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_rechargerecords.cretime
     *
     * @param cretime the value for tra_rechargerecords.cretime
     *
     * @mbggenerated
     */
    public void setCretime(Date cretime) {
        this.cretime = cretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_rechargerecords.paytype
     *
     * @return the value of tra_rechargerecords.paytype
     *
     * @mbggenerated
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_rechargerecords.paytype
     *
     * @param paytype the value for tra_rechargerecords.paytype
     *
     * @mbggenerated
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_rechargerecords.source
     *
     * @return the value of tra_rechargerecords.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_rechargerecords.source
     *
     * @param source the value for tra_rechargerecords.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }
}