package com.cpf.beans.transaction;

import java.util.Date;

public class TraSpecialorders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.speorderid
     *
     * @mbggenerated
     */
    private String speorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.Specialid
     *
     * @mbggenerated
     */
    private String specialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.ordercode
     *
     * @mbggenerated
     */
    private String ordercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.Sellerid
     *
     * @mbggenerated
     */
    private String sellerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.buyerid
     *
     * @mbggenerated
     */
    private String buyerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.Guaranteedamount
     *
     * @mbggenerated
     */
    private Double guaranteedamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.ispay
     *
     * @mbggenerated
     */
    private String ispay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.paytime
     *
     * @mbggenerated
     */
    private Date paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.buyername
     *
     * @mbggenerated
     */
    private String buyername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.buyerphone
     *
     * @mbggenerated
     */
    private String buyerphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.buyeraddress
     *
     * @mbggenerated
     */
    private String buyeraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.Expresscompany
     *
     * @mbggenerated
     */
    private String expresscompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.trackingnumber
     *
     * @mbggenerated
     */
    private String trackingnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders.isok
     *
     * @mbggenerated
     */
    private String isok;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.speorderid
     *
     * @return the value of tra_specialorders.speorderid
     *
     * @mbggenerated
     */
    public String getSpeorderid() {
        return speorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.speorderid
     *
     * @param speorderid the value for tra_specialorders.speorderid
     *
     * @mbggenerated
     */
    public void setSpeorderid(String speorderid) {
        this.speorderid = speorderid == null ? null : speorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.Specialid
     *
     * @return the value of tra_specialorders.Specialid
     *
     * @mbggenerated
     */
    public String getSpecialid() {
        return specialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.Specialid
     *
     * @param specialid the value for tra_specialorders.Specialid
     *
     * @mbggenerated
     */
    public void setSpecialid(String specialid) {
        this.specialid = specialid == null ? null : specialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.createtime
     *
     * @return the value of tra_specialorders.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.createtime
     *
     * @param createtime the value for tra_specialorders.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.ordercode
     *
     * @return the value of tra_specialorders.ordercode
     *
     * @mbggenerated
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.ordercode
     *
     * @param ordercode the value for tra_specialorders.ordercode
     *
     * @mbggenerated
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode == null ? null : ordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.Sellerid
     *
     * @return the value of tra_specialorders.Sellerid
     *
     * @mbggenerated
     */
    public String getSellerid() {
        return sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.Sellerid
     *
     * @param sellerid the value for tra_specialorders.Sellerid
     *
     * @mbggenerated
     */
    public void setSellerid(String sellerid) {
        this.sellerid = sellerid == null ? null : sellerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.buyerid
     *
     * @return the value of tra_specialorders.buyerid
     *
     * @mbggenerated
     */
    public String getBuyerid() {
        return buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.buyerid
     *
     * @param buyerid the value for tra_specialorders.buyerid
     *
     * @mbggenerated
     */
    public void setBuyerid(String buyerid) {
        this.buyerid = buyerid == null ? null : buyerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.Guaranteedamount
     *
     * @return the value of tra_specialorders.Guaranteedamount
     *
     * @mbggenerated
     */
    public Double getGuaranteedamount() {
        return guaranteedamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.Guaranteedamount
     *
     * @param guaranteedamount the value for tra_specialorders.Guaranteedamount
     *
     * @mbggenerated
     */
    public void setGuaranteedamount(Double guaranteedamount) {
        this.guaranteedamount = guaranteedamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.state
     *
     * @return the value of tra_specialorders.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.state
     *
     * @param state the value for tra_specialorders.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.ispay
     *
     * @return the value of tra_specialorders.ispay
     *
     * @mbggenerated
     */
    public String getIspay() {
        return ispay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.ispay
     *
     * @param ispay the value for tra_specialorders.ispay
     *
     * @mbggenerated
     */
    public void setIspay(String ispay) {
        this.ispay = ispay == null ? null : ispay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.paytime
     *
     * @return the value of tra_specialorders.paytime
     *
     * @mbggenerated
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.paytime
     *
     * @param paytime the value for tra_specialorders.paytime
     *
     * @mbggenerated
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.buyername
     *
     * @return the value of tra_specialorders.buyername
     *
     * @mbggenerated
     */
    public String getBuyername() {
        return buyername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.buyername
     *
     * @param buyername the value for tra_specialorders.buyername
     *
     * @mbggenerated
     */
    public void setBuyername(String buyername) {
        this.buyername = buyername == null ? null : buyername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.buyerphone
     *
     * @return the value of tra_specialorders.buyerphone
     *
     * @mbggenerated
     */
    public String getBuyerphone() {
        return buyerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.buyerphone
     *
     * @param buyerphone the value for tra_specialorders.buyerphone
     *
     * @mbggenerated
     */
    public void setBuyerphone(String buyerphone) {
        this.buyerphone = buyerphone == null ? null : buyerphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.buyeraddress
     *
     * @return the value of tra_specialorders.buyeraddress
     *
     * @mbggenerated
     */
    public String getBuyeraddress() {
        return buyeraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.buyeraddress
     *
     * @param buyeraddress the value for tra_specialorders.buyeraddress
     *
     * @mbggenerated
     */
    public void setBuyeraddress(String buyeraddress) {
        this.buyeraddress = buyeraddress == null ? null : buyeraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.Expresscompany
     *
     * @return the value of tra_specialorders.Expresscompany
     *
     * @mbggenerated
     */
    public String getExpresscompany() {
        return expresscompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.Expresscompany
     *
     * @param expresscompany the value for tra_specialorders.Expresscompany
     *
     * @mbggenerated
     */
    public void setExpresscompany(String expresscompany) {
        this.expresscompany = expresscompany == null ? null : expresscompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.trackingnumber
     *
     * @return the value of tra_specialorders.trackingnumber
     *
     * @mbggenerated
     */
    public String getTrackingnumber() {
        return trackingnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.trackingnumber
     *
     * @param trackingnumber the value for tra_specialorders.trackingnumber
     *
     * @mbggenerated
     */
    public void setTrackingnumber(String trackingnumber) {
        this.trackingnumber = trackingnumber == null ? null : trackingnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders.isok
     *
     * @return the value of tra_specialorders.isok
     *
     * @mbggenerated
     */
    public String getIsok() {
        return isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders.isok
     *
     * @param isok the value for tra_specialorders.isok
     *
     * @mbggenerated
     */
    public void setIsok(String isok) {
        this.isok = isok == null ? null : isok.trim();
    }
}