package com.cpf.beans.transaction;

public class TraSpecialordersDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders_details.speorderid
     *
     * @mbggenerated
     */
    private String speorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders_details.specialdetailsid
     *
     * @mbggenerated
     */
    private String specialdetailsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders_details.productid
     *
     * @mbggenerated
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders_details.dealprice
     *
     * @mbggenerated
     */
    private Double dealprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_specialorders_details.nums
     *
     * @mbggenerated
     */
    private Long nums;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders_details.speorderid
     *
     * @return the value of tra_specialorders_details.speorderid
     *
     * @mbggenerated
     */
    public String getSpeorderid() {
        return speorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders_details.speorderid
     *
     * @param speorderid the value for tra_specialorders_details.speorderid
     *
     * @mbggenerated
     */
    public void setSpeorderid(String speorderid) {
        this.speorderid = speorderid == null ? null : speorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders_details.specialdetailsid
     *
     * @return the value of tra_specialorders_details.specialdetailsid
     *
     * @mbggenerated
     */
    public String getSpecialdetailsid() {
        return specialdetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders_details.specialdetailsid
     *
     * @param specialdetailsid the value for tra_specialorders_details.specialdetailsid
     *
     * @mbggenerated
     */
    public void setSpecialdetailsid(String specialdetailsid) {
        this.specialdetailsid = specialdetailsid == null ? null : specialdetailsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders_details.productid
     *
     * @return the value of tra_specialorders_details.productid
     *
     * @mbggenerated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders_details.productid
     *
     * @param productid the value for tra_specialorders_details.productid
     *
     * @mbggenerated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders_details.dealprice
     *
     * @return the value of tra_specialorders_details.dealprice
     *
     * @mbggenerated
     */
    public Double getDealprice() {
        return dealprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders_details.dealprice
     *
     * @param dealprice the value for tra_specialorders_details.dealprice
     *
     * @mbggenerated
     */
    public void setDealprice(Double dealprice) {
        this.dealprice = dealprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_specialorders_details.nums
     *
     * @return the value of tra_specialorders_details.nums
     *
     * @mbggenerated
     */
    public Long getNums() {
        return nums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_specialorders_details.nums
     *
     * @param nums the value for tra_specialorders_details.nums
     *
     * @mbggenerated
     */
    public void setNums(Long nums) {
        this.nums = nums;
    }
}