package com.cpf.beans.transaction;

import java.util.Date;

public class TraTransactionrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_transactionrecord.recordid
     *
     * @mbggenerated
     */
    private String recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_transactionrecord.Amount
     *
     * @mbggenerated
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_transactionrecord.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_transactionrecord.tratime
     *
     * @mbggenerated
     */
    private Date tratime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_transactionrecord.orderid
     *
     * @mbggenerated
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_transactionrecord.paytype
     *
     * @mbggenerated
     */
    private String paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_transactionrecord.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_transactionrecord.recordid
     *
     * @return the value of tra_transactionrecord.recordid
     *
     * @mbggenerated
     */
    public String getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_transactionrecord.recordid
     *
     * @param recordid the value for tra_transactionrecord.recordid
     *
     * @mbggenerated
     */
    public void setRecordid(String recordid) {
        this.recordid = recordid == null ? null : recordid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_transactionrecord.Amount
     *
     * @return the value of tra_transactionrecord.Amount
     *
     * @mbggenerated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_transactionrecord.Amount
     *
     * @param amount the value for tra_transactionrecord.Amount
     *
     * @mbggenerated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_transactionrecord.source
     *
     * @return the value of tra_transactionrecord.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_transactionrecord.source
     *
     * @param source the value for tra_transactionrecord.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_transactionrecord.tratime
     *
     * @return the value of tra_transactionrecord.tratime
     *
     * @mbggenerated
     */
    public Date getTratime() {
        return tratime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_transactionrecord.tratime
     *
     * @param tratime the value for tra_transactionrecord.tratime
     *
     * @mbggenerated
     */
    public void setTratime(Date tratime) {
        this.tratime = tratime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_transactionrecord.orderid
     *
     * @return the value of tra_transactionrecord.orderid
     *
     * @mbggenerated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_transactionrecord.orderid
     *
     * @param orderid the value for tra_transactionrecord.orderid
     *
     * @mbggenerated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_transactionrecord.paytype
     *
     * @return the value of tra_transactionrecord.paytype
     *
     * @mbggenerated
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_transactionrecord.paytype
     *
     * @param paytype the value for tra_transactionrecord.paytype
     *
     * @mbggenerated
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_transactionrecord.userid
     *
     * @return the value of tra_transactionrecord.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_transactionrecord.userid
     *
     * @param userid the value for tra_transactionrecord.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}