package com.cpf.beans.transaction;

public class TraTrading {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_trading.tradingid
     *
     * @mbggenerated
     */
    private String tradingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_trading.productid
     *
     * @mbggenerated
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_trading.toused
     *
     * @mbggenerated
     */
    private String toused;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_trading.isshelf
     *
     * @mbggenerated
     */
    private String isshelf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_trading.Startingprice
     *
     * @mbggenerated
     */
    private Double startingprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_trading.Reserveprice
     *
     * @mbggenerated
     */
    private Double reserveprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_trading.isNoreserveprice
     *
     * @mbggenerated
     */
    private String isnoreserveprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_trading.专场id
     *
     * @mbggenerated
     */
    private String zcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_trading.Barterneeds
     *
     * @mbggenerated
     */
    private String barterneeds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_trading.fare
     *
     * @mbggenerated
     */
    private String fare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_trading.onInsurance
     *
     * @mbggenerated
     */
    private String oninsurance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_trading.onReturns
     *
     * @mbggenerated
     */
    private String onreturns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tra_trading.isAudit
     *
     * @mbggenerated
     */
    private String isaudit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_trading.tradingid
     *
     * @return the value of tra_trading.tradingid
     *
     * @mbggenerated
     */
    public String getTradingid() {
        return tradingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_trading.tradingid
     *
     * @param tradingid the value for tra_trading.tradingid
     *
     * @mbggenerated
     */
    public void setTradingid(String tradingid) {
        this.tradingid = tradingid == null ? null : tradingid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_trading.productid
     *
     * @return the value of tra_trading.productid
     *
     * @mbggenerated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_trading.productid
     *
     * @param productid the value for tra_trading.productid
     *
     * @mbggenerated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_trading.toused
     *
     * @return the value of tra_trading.toused
     *
     * @mbggenerated
     */
    public String getToused() {
        return toused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_trading.toused
     *
     * @param toused the value for tra_trading.toused
     *
     * @mbggenerated
     */
    public void setToused(String toused) {
        this.toused = toused == null ? null : toused.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_trading.isshelf
     *
     * @return the value of tra_trading.isshelf
     *
     * @mbggenerated
     */
    public String getIsshelf() {
        return isshelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_trading.isshelf
     *
     * @param isshelf the value for tra_trading.isshelf
     *
     * @mbggenerated
     */
    public void setIsshelf(String isshelf) {
        this.isshelf = isshelf == null ? null : isshelf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_trading.Startingprice
     *
     * @return the value of tra_trading.Startingprice
     *
     * @mbggenerated
     */
    public Double getStartingprice() {
        return startingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_trading.Startingprice
     *
     * @param startingprice the value for tra_trading.Startingprice
     *
     * @mbggenerated
     */
    public void setStartingprice(Double startingprice) {
        this.startingprice = startingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_trading.Reserveprice
     *
     * @return the value of tra_trading.Reserveprice
     *
     * @mbggenerated
     */
    public Double getReserveprice() {
        return reserveprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_trading.Reserveprice
     *
     * @param reserveprice the value for tra_trading.Reserveprice
     *
     * @mbggenerated
     */
    public void setReserveprice(Double reserveprice) {
        this.reserveprice = reserveprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_trading.isNoreserveprice
     *
     * @return the value of tra_trading.isNoreserveprice
     *
     * @mbggenerated
     */
    public String getIsnoreserveprice() {
        return isnoreserveprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_trading.isNoreserveprice
     *
     * @param isnoreserveprice the value for tra_trading.isNoreserveprice
     *
     * @mbggenerated
     */
    public void setIsnoreserveprice(String isnoreserveprice) {
        this.isnoreserveprice = isnoreserveprice == null ? null : isnoreserveprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_trading.专场id
     *
     * @return the value of tra_trading.专场id
     *
     * @mbggenerated
     */
    public String getZcid() {
        return zcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_trading.专场id
     *
     * @param 专场id the value for tra_trading.专场id
     *
     * @mbggenerated
     */
    public void setZcid(String zcid) {
        this.zcid = zcid == null ? null : zcid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_trading.Barterneeds
     *
     * @return the value of tra_trading.Barterneeds
     *
     * @mbggenerated
     */
    public String getBarterneeds() {
        return barterneeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_trading.Barterneeds
     *
     * @param barterneeds the value for tra_trading.Barterneeds
     *
     * @mbggenerated
     */
    public void setBarterneeds(String barterneeds) {
        this.barterneeds = barterneeds == null ? null : barterneeds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_trading.fare
     *
     * @return the value of tra_trading.fare
     *
     * @mbggenerated
     */
    public String getFare() {
        return fare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_trading.fare
     *
     * @param fare the value for tra_trading.fare
     *
     * @mbggenerated
     */
    public void setFare(String fare) {
        this.fare = fare == null ? null : fare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_trading.onInsurance
     *
     * @return the value of tra_trading.onInsurance
     *
     * @mbggenerated
     */
    public String getOninsurance() {
        return oninsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_trading.onInsurance
     *
     * @param oninsurance the value for tra_trading.onInsurance
     *
     * @mbggenerated
     */
    public void setOninsurance(String oninsurance) {
        this.oninsurance = oninsurance == null ? null : oninsurance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_trading.onReturns
     *
     * @return the value of tra_trading.onReturns
     *
     * @mbggenerated
     */
    public String getOnreturns() {
        return onreturns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_trading.onReturns
     *
     * @param onreturns the value for tra_trading.onReturns
     *
     * @mbggenerated
     */
    public void setOnreturns(String onreturns) {
        this.onreturns = onreturns == null ? null : onreturns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tra_trading.isAudit
     *
     * @return the value of tra_trading.isAudit
     *
     * @mbggenerated
     */
    public String getIsaudit() {
        return isaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tra_trading.isAudit
     *
     * @param isaudit the value for tra_trading.isAudit
     *
     * @mbggenerated
     */
    public void setIsaudit(String isaudit) {
        this.isaudit = isaudit == null ? null : isaudit.trim();
    }
}